version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./.cache/pip:/root/.cache/pip
    environment:
      - ENV=dev
